#           ______      __
#          / ____/___  / /_____
#         / / __/ __ \/ __/ __ \
#        / /_/ / /_/ / /_/ /_/ /
#   _____\____/\____/\__/\____/
#  / ___/__  _______/ /____  ____ ___
#  \__ \/ / / / ___/ __/ _ \/ __ `__ \
# ___/ / /_/ (__  ) /_/  __/ / / / / /
#/____/\__, /____/\__/\___/_/ /_/ /_/
#     /____/
# GoTo System | Version 1.0-SNAPSHOT

no-perms: "&cYou don't have the permission to perform this command!"
usage: "&cUsage: /goto <server>"
